onlyBuiltDependencies:
  - electron
  - usb
  - better-sqlite3-multiple-ciphers
  - tiny-secp256k1
  - argon2
blockExoticSubdeps: false
allowBuilds:
  argon2: true
  better-sqlite3-multiple-ciphers: true
  blake-hash: true
  electron: true
  electron-winstaller: true
  esbuild: true
  node-hid: true
  protobufjs: true
  tiny-secp256k1: true
  usb: true
