overrides:
  protobufjs: "7.6.5"
  tar: "7.5.19"

onlyBuiltDependencies:
  - electron
  - usb
  - better-sqlite3-multiple-ciphers
  - tiny-secp256k1
  - argon2
blockExoticSubdeps: false
allowBuilds:
  '@stellar/stellar-sdk': false
  argon2: true
  better-sqlite3-multiple-ciphers: true
  blake-hash: true
  electron: true
  electron-winstaller: true
  esbuild: true
  node-hid: true
  protobufjs: true
  tiny-secp256k1: true
  usb: true
minimumReleaseAgeExclude:
  - esbuild@0.24.3
  - estree-util-value-to-estree@3.3.3
  - cookie@0.7.0
  - tiny-secp256k1@1.1.7
  - electron@35.7.5 || 38.8.6 || 39.8.1 || 39.8.5
  - better-sqlite3-multiple-ciphers@12.11.1
  - valibot@1.2.0
  - elliptic@6.6.2
  - '@remix-run/router@1.23.2'
  - '@remix-run/node@2.17.2'
  - tar@7.5.3 || 7.5.4 || 7.5.7 || 7.5.8 || 7.5.10 || 7.5.11 || 7.5.16 || 7.5.19
  - vite@6.4.2 || 6.4.3
  - protobufjs@7.5.5 || 7.5.6 || 7.5.8 || 7.6.1 || 7.6.3 || 7.6.5
  - uuid@11.1.1
  - '@remix-run/server-runtime@2.17.3 || 2.17.5'
  - turbo-stream@3.0.0
